### ISSUE TITLE
Where to enter IP address of the Philips Hue Bridge?

### ISSUE THREAD

**Issue by hive-worker** [bitfocus/companion-module-phillips-hue#5]
When I used postman to control the lights both the API key and the IP address of the bridge were needed. I can see where the key is entered but there isn't a place for the IP address. Can you please guide on this issue?

**Comment by MegaAdragon** [comment]
This should be resolved by #6. You can either select a discovered bridge or enter a custom IP address in the module configuration.

**Comment by James-stgeorges** [comment]
I'd like to report this problem as well... I've created the username using the alternate method (because the plugin wasn't creating it correctly). When done, the plugin reports that it is connected but it won't produce a list of available lights, groups, etc...

Near as I can tell it must be failing to send the get request to the right IP, and I'm wondering if there's a way to set the IP of the bridge directly (I'm assuming it isn't being discovered properly). But I don't see a spot for the IP Address to be entered manually in the module configuration. 

Any suggestions are very much welcome! 

Cheers,
James

**Comment by MegaAdragon** [comment]
@James-stgeorges 
Did you make sure to use the newest version of this repo? I'm guess companion is still linking to the old version of this plugin.

**Comment by James-stgeorges** [comment]
> @James-stgeorges Did you make sure to use the newest version of this repo? I guess companion is still linking to the old version of this plugin.

I'm running companion on Raspberry Pi using the most current stable release which at present is 2.21+4443-98594c92

Looking at the package.json the reference for the companion-module-phillipshue: is github:bitfocus/companion-module-phillips-hue#v0.0.6 which according to this repository is supposed to be the stable release from January but I know there has been several updates since then that cover this problem... and I'm a little unclear as to how to link to the newest version in this repo... I can change the reference in the package.json but I don't have a clear idea of what to change it too... 

Any suggestions welcome for sure!

James

**Comment by James-stgeorges** [comment]
> Easiest way (or at least the way I currently use):
> 
> * Go into `companion/module-local-dev`
> * Clone this repo: `git clone https://github.com/bitfocus/companion-module-phillips-hue.git`
> * Remove the older module version from `companion/node_modules/companion-module-phillips-hue`
> 
> Now you should have the newest version of this repo.

That Did it!!! You're AMAZING!!! :-) Thank you so so much to all of you for working through it with me... its so very appreciated!
